pipeline {
    environment {
        registry = "iavtar/is-orchestration-service"
        registryCredentials = "docker-creds"
        dockerImage = ''
    }
    agent any
    stages{
        stage('Checkout SCM'){
            steps{
                git credentialsId: 'git', url: 'http://iavtar@bitbucket.org/iavtar-ecom/orchestration-service.git'
            }
        }
        stage('Build-Project'){
            steps{
                sh 'mvn clean install package'
            }
        }   
          stage('SAST Analysis'){
          steps{
               withSonarQubeEnv('sonar-6'){
               sh 'mvn sonar:sonar'
           }
          }
        }
        stage('Build-Docker-Image'){
            steps{
                script{
                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                }
            }
        }
         stage('Upload-Docker-Image-Artifact'){
           steps{
               script{
                   docker.withRegistry('', registryCredentials){
                       dockerImage.push("$BUILD_NUMBER")
                       dockerImage.push("latest")
                   }
               }
           }
        }
        stage('Pull-image'){
           steps{
                sh "docker rmi $registry:$BUILD_NUMBER"
           }
        }
         stage('Deploy'){
           steps{
                sh "docker-compose down"
         		sh "docker-compose up -d"
           }
        }
    }
}