pipeline {
    environment {
        registry = "iavtar/is-product-service"
        registryCredentials = "docker-creds"
        dockerImage = ''
    }
    agent any
    stages{
        stage('Checkout SCM'){
            steps{
                git credentialsId: 'git', url: 'http://iavtar@bitbucket.org/iavtar-ecom/product-service.git'
            }
        }
        stage('Build-Project'){
            steps{
                sh 'mvn clean install package'
            }
        }   
        stage('Build-Docker-Image'){
            steps{
                script{
                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                }
            }
        }
        stage('Upload-Docker-Image-Artifact'){
           steps{
               script{
                   docker.withRegistry('', registryCredentials){
                       dockerImage.push()
                   }
               }
           }
        }
        stage('Pull-image'){
           steps{
                sh "docker rmi $registry:$BUILD_NUMBER"
           }
        }
        
    }
}