pipeline {
    environment {
        registry = "iavtar/is-gateway-service"
        registryCredentials = "docker-creds"
        dockerImage = ''
    }
    agent any
    stages{
        stage('Checkout SCM'){
            steps{
                git credentialsId: 'git', url: 'http://iavtar@bitbucket.org/iavtar-ecom/gateway-service.git'
            }
        }
        stage('Build-Project'){
            steps{
                sh 'mvn clean install package'
            }
        }   
        stage('Build-Docker-Image'){
            steps{
                script{
                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                }
            }
        }
        stage('Upload-Docker-Image-Artifact'){
           steps{
               script{
                   docker.withRegistry('', registryCredentials){\
                   	   dockerImage.push("$BUILD_NUMBER")
                       dockerImage.push("latest")
                   }
               }
           }
        }
        stage('Pull-image'){
           steps{
                sh "docker rmi $registry:$BUILD_NUMBER"
           }
        }
        stage('Deploy'){
           steps{
                sh "docker-compose down"
         		sh "docker-compose up -d"
           }
        }
        
    }
}